#!/usr/bin/env python3
"""
Banc de preguntes de cultura general del web Memòria.

Cada pregunta porta: text, resposta bona, tres respostes dolentes,
EXPLICACIÓ, tema i nivell (0 fàcil · 1 mitjà · 2 difícil).

Criteris:
  · només fets estables: res que depengui de l'actualitat ni de qui mana ara
  · res discutible (s'eviten "el riu més llarg del món" i companyia)
  · l'explicació ha d'ensenyar alguna cosa, no repetir la resposta
  · les respostes dolentes han de ser creïbles, no absurdes
"""

# (pregunta, bona, [dolentes], explicació, tema, nivell)
BANC = [

# ══════════════ NATURA I COS ══════════════
('Quantes potes té una aranya?', '8', ['6', '10', '4'],
 "Les aranyes en tenen vuit; els insectes, com les formigues o les mosques, en tenen sis. Per això les aranyes no són insectes: són aràcnids.",
 'natura', 0),
('Quin animal fa la mel?', "L'abella", ['La vespa', 'La formiga', 'El borinot'],
 "Les abelles xuclen el nèctar de les flors i el transformen en mel dins del rusc, on la guarden com a reserva de menjar per a l'hivern.",
 'natura', 0),
('De quin animal ve la llana?', "De l'ovella", ['De la vaca', 'Del porc', 'Del cavall'],
 "La llana és el pèl de l'ovella. Se li talla a l'estiu, no li fa cap mal i li torna a créixer per a l'hivern.",
 'natura', 0),
('Quin òrgan bomba la sang pel cos?', 'El cor', ['El fetge', 'El pulmó', 'El ronyó'],
 "El cor és un múscul que es contrau tota la vida sense parar i empeny la sang per les artèries fins a l'últim racó del cos.",
 'natura', 0),
('Què necessiten les plantes per créixer, a més d’aigua?', 'Llum', ['Sal', 'Sorra', 'Vent'],
 "Amb la llum les plantes fabriquen el seu propi aliment a les fulles. Per això una planta dins d'un armari fosc s'acaba morint encara que la reguis.",
 'natura', 0),
('Quants dits té una mà?', '5', ['4', '6', '10'],
 "Cinc: polze, índex, mig, anular i petit. El polze és el que ens diferencia: es pot posar davant dels altres i ens deixa agafar coses.",
 'natura', 0),
('Quin és l’animal més gran del planeta?', 'La balena blava', ["L'elefant", 'La girafa', 'El tauró blanc'],
 "La balena blava pot passar dels 25 metres i les 100 tones. L'elefant, que és el més gran de terra ferma, no arriba ni a les 7 tones.",
 'natura', 1),
('Quin és l’animal terrestre més ràpid?', 'El guepard', ['El cavall', 'El lleó', 'La llebre'],
 "El guepard passa dels 100 km/h, però només durant uns segons: s'escalfa tant que ha de parar de seguida.",
 'natura', 1),
('Quin metall és líquid a temperatura ambient?', 'El mercuri', ['El plom', "L'estany", 'El coure'],
 "És l'únic metall que a temperatura normal és líquid; per això s'utilitzava als termòmetres antics. La resta s'han d'escalfar centenars de graus per fondre'ls.",
 'natura', 1),
('Quantes potes té un insecte?', '6', ['4', '8', '10'],
 "Sis, sempre. És justament el que defineix un insecte, i el que el separa de les aranyes, que en tenen vuit.",
 'natura', 1),
('Què fa que les fulles siguin verdes?', 'La clorofil·la', ['La saba', 'El sol', "L'aigua"],
 "La clorofil·la és la substància que aprofita la llum per alimentar la planta. A la tardor la planta la deixa de fabricar, i llavors es veuen els grocs i els vermells que sempre hi eren a sota.",
 'natura', 1),
('Quants litres de sang té, aproximadament, una persona adulta?', '5', ['1', '10', '20'],
 "Uns cinc litres, més o menys el que cabria en cinc cartrons de llet. Tota aquesta sang fa la volta al cos en menys d'un minut.",
 'natura', 1),
('Quin gas necessitem per respirar?', "L'oxigen", ['El nitrogen', "L'hidrogen", 'El diòxid de carboni'],
 "Agafem oxigen de l'aire i deixem anar diòxid de carboni. Les plantes fan exactament el contrari, i per això ens necessitem els uns als altres.",
 'natura', 1),
('Quin animal canvia de color per amagar-se?', 'El camaleó', ['La granota', 'La serp', 'El conill'],
 "El camaleó canvia de color movent uns cristalls que té a la pell. Ho fa per amagar-se, però també segons la temperatura i l'estat d'ànim.",
 'natura', 1),
('Quin gas absorbeixen les plantes per fer la fotosíntesi?', 'El diòxid de carboni', ["L'oxigen", 'El nitrogen', "L'hidrogen"],
 "Agafen diòxid de carboni de l'aire i, amb la llum del sol i l'aigua, fabriquen el seu aliment. L'oxigen que deixen anar és, de fet, un residu d'aquest procés.",
 'natura', 2),
('Quin és l’os més llarg del cos humà?', 'El fèmur', ["L'húmer", 'La tíbia', 'La clavícula'],
 "El fèmur és l'os de la cuixa i fa aproximadament una quarta part de l'alçada de la persona. També és el més resistent.",
 'natura', 2),
('Quina cèl·lula transporta l’oxigen per la sang?', 'El glòbul vermell', ['El glòbul blanc', 'La plaqueta', 'La neurona'],
 "Els glòbuls vermells porten l'oxigen dels pulmons a tot el cos. Els blancs defensen de les infeccions i les plaquetes tapen les ferides.",
 'natura', 2),
('Quin element químic té el símbol Fe?', 'El ferro', ['El fòsfor', 'El fluor', 'El franci'],
 "Ve del llatí *ferrum*. Molts símbols vénen del llatí i per això no s'assemblen al nom català: el plom és Pb (*plumbum*) i l'or és Au (*aurum*).",
 'natura', 2),
('Quants ossos té, aproximadament, un adult?', '206', ['106', '306', '406'],
 "Un nadó en té uns 300, però molts es van soldant mentre creix. Un adult en té uns 206, i més de la meitat són a les mans i als peus.",
 'natura', 2),
('Quina part de la cèl·lula guarda la informació genètica?', 'El nucli', ['La membrana', 'El citoplasma', 'El ribosoma'],
 "Al nucli hi ha l'ADN, que és el manual d'instruccions de l'ésser viu. La membrana és la paret de la cèl·lula i el citoplasma, el que l'omple.",
 'natura', 2),
('A quina temperatura bull l’aigua al nivell del mar?', '100 °C', ['80 °C', '120 °C', '90 °C'],
 "A 100 graus, però només al nivell del mar. A la muntanya hi ha menys pressió i bull abans: per això a dalt les llegums triguen més a coure's.",
 'natura', 2),

# ══════════════ MÓN ══════════════
('Quina és la capital de França?', 'París', ['Lió', 'Marsella', 'Niça'],
 "París és la capital i la ciutat més gran de França. Lió i Marsella són les dues següents en població.",
 'mon', 0),
('Quin mar banya Barcelona?', 'El Mediterrani', ["L'Atlàntic", 'El Cantàbric', 'El mar del Nord'],
 "El Mediterrani és un mar gairebé tancat: només es comunica amb l'Atlàntic per l'estret de Gibraltar, que fa tot just 14 quilòmetres.",
 'mon', 0),
('Quin és l’oceà més gran del món?', 'El Pacífic', ["L'Atlàntic", "L'Índic", "L'Àrtic"],
 "El Pacífic ell sol ocupa gairebé un terç de la superfície del planeta: hi cabrien tots els continents junts.",
 'mon', 0),
('Quantes estacions té l’any?', '4', ['2', '3', '6'],
 "Primavera, estiu, tardor i hivern. Passen perquè la Terra està una mica inclinada, i per això quan aquí és estiu, a l'altre hemisferi és hivern.",
 'mon', 0),
('En quin continent és Egipte?', 'Àfrica', ['Àsia', 'Europa', 'Amèrica'],
 "Egipte és al nord-est d'Àfrica, tot i que un tros petit, la península del Sinaí, ja és a Àsia.",
 'mon', 0),
('Quin és el satèl·lit natural de la Terra?', 'La Lluna', ['Mart', 'Venus', 'El Sol'],
 "La Lluna dona voltes al voltant de la Terra. Mart i Venus són planetes que giren al voltant del Sol, i el Sol és un estel.",
 'mon', 1),
('Quin és el planeta més a prop del Sol?', 'Mercuri', ['Venus', 'Mart', 'La Terra'],
 "L'ordre és Mercuri, Venus, la Terra i Mart. Curiosament el més calent no és Mercuri sinó Venus, perquè té una atmosfera espessa que hi reté la calor.",
 'mon', 1),
('Quin país té forma de bota?', 'Itàlia', ['Grècia', 'Portugal', 'Noruega'],
 "La península itàlica té forma de bota i sembla que doni una puntada de peu a Sicília, que és just davant de la punta.",
 'mon', 1),
('Quina és la muntanya més alta del món?', "L'Everest", ['El K2', 'El Mont Blanc', 'El Kilimanjaro'],
 "L'Everest arriba als 8.849 metres, a l'Himàlaia, entre el Nepal i el Tibet. El K2 és el segon, i molt més perillós de pujar.",
 'mon', 1),
('Quin és el país més extens del món?', 'Rússia', ['El Canadà', 'La Xina', 'El Brasil'],
 "Rússia ocupa més d'una desena part de tota la terra ferma del planeta i té onze franges horàries: quan a un extrem es lleven, a l'altre ja sopen.",
 'mon', 1),
('Quin desert càlid és el més extens del món?', 'El Sàhara', ['El Gobi', "L'Atacama", 'El Kalahari'],
 "El Sàhara travessa el nord d'Àfrica i és gairebé tan gran com els Estats Units. (El desert més gran de tots és l'Antàrtida, però aquell és de gel.)",
 'mon', 2),
('Quin estret separa Europa d’Àfrica?', 'Gibraltar', ['El Bòsfor', 'Ormuz', 'Malaca'],
 "A l'estret de Gibraltar, Europa i Àfrica queden a 14 quilòmetres l'una de l'altra: des de la costa es veu perfectament l'altre continent.",
 'mon', 2),
("Quina és la capital d'Austràlia?", 'Canberra', ['Sydney', 'Melbourne', 'Perth'],
 "Sydney i Melbourne es barallaven per ser-ho, i la solució va ser construir una ciutat nova entre totes dues: Canberra.",
 'mon', 2),
('Quin planeta té els anells més visibles?', 'Saturn', ['Júpiter', 'Urà', 'Neptú'],
 "Els anells de Saturn es veuen amb un telescopi senzill i són fets de milions de trossos de gel i roca. Júpiter, Urà i Neptú també en tenen, però molt fins.",
 'mon', 2),
('Quina llengua té més parlants com a llengua materna?', 'El xinès mandarí', ["L'anglès", "L'espanyol", "L'hindi"],
 "El mandarí és la llengua materna de molta més gent que cap altra. L'anglès, en canvi, és la que més es parla com a segona llengua.",
 'mon', 2),
('Per quin país passa el riu Danubi?', 'Hongria', ['Portugal', 'Irlanda', 'Noruega'],
 "El Danubi travessa deu països i passa per quatre capitals: Viena, Bratislava, Budapest i Belgrad. Cap altre riu del món en toca tantes.",
 'mon', 2),
('Quina és la ciutat més poblada d’Espanya?', 'Madrid', ['Barcelona', 'València', 'Sevilla'],
 "Madrid és la primera i Barcelona la segona. Madrid, a més, és de les poques capitals europees que no és vora d'un riu gran ni del mar.",
 'mon', 1),

# ══════════════ HISTÒRIA I ART ══════════════
('Qui va dissenyar la Sagrada Família?', 'Antoni Gaudí', ['Lluís Domènech i Montaner', 'Josep Puig i Cadafalch', 'Ildefons Cerdà'],
 "Gaudí hi va treballar més de quaranta anys i s'hi va acabar instal·lant. Sabia que no la veuria acabada i va deixar maquetes perquè altres poguessin continuar.",
 'historia', 0),
('Qui va pintar el Guernica?', 'Picasso', ['Dalí', 'Miró', 'Velázquez'],
 "Picasso el va pintar el 1937, després del bombardeig del poble de Gernika. És tot en blanc, negre i gris, com les fotografies dels diaris de l'època.",
 'historia', 1),
('Qui va escriure el Quixot?', 'Cervantes', ['Lope de Vega', 'Quevedo', 'Góngora'],
 "Miguel de Cervantes el va publicar en dues parts, el 1605 i el 1615. Està considerada la primera novel·la moderna.",
 'historia', 1),
('Quin instrument té 88 tecles?', 'El piano', ["L'orgue", "L'acordió", 'El clavicèmbal'],
 "Un piano de cua en té 88: 52 de blanques i 36 de negres. És el recorregut que abasta pràcticament tots els sons que fa servir la música.",
 'historia', 1),
('En quin any va arribar l’home a la Lluna?', '1969', ['1959', '1972', '1965'],
 "El 20 de juliol de 1969, amb l'Apol·lo 11. Hi van tornar cinc vegades més, i des del 1972 no hi ha pujat ningú.",
 'historia', 1),
('Qui va escriure el Tirant lo Blanc?', 'Joanot Martorell', ['Ausiàs March', 'Ramon Llull', 'Jacint Verdaguer'],
 "És del segle XV i està escrit en català. Cervantes en parla dins del Quixot i el salva de la crema de llibres dient-ne meravelles.",
 'historia', 2),
('En quin any va caure el mur de Berlín?', '1989', ['1979', '1991', '1985'],
 "El 9 de novembre de 1989. Havia partit la ciutat durant 28 anys i la seva caiguda va ser el senyal del final de la guerra freda.",
 'historia', 2),
('En quin segle va començar la Revolució Francesa?', 'Al segle XVIII', ['Al segle XVII', 'Al segle XIX', 'Al segle XVI'],
 "Va començar el 1789, que és segle XVIII: els anys que comencen per 17 pertanyen al segle divuit, perquè el segle I van ser els anys de l'1 al 100.",
 'historia', 2),
('Qui va formular la teoria de la relativitat?', 'Einstein', ['Newton', 'Galileu', 'Bohr'],
 "Albert Einstein, entre el 1905 i el 1915. Va demostrar que el temps no passa igual a tot arreu: com més de pressa vas, més a poc a poc va el teu rellotge.",
 'historia', 2),
('Qui va compondre la Novena Simfonia, amb l’Himne a l’Alegria?', 'Beethoven', ['Mozart', 'Bach', 'Vivaldi'],
 "Beethoven la va acabar el 1824, quan ja era completament sord: la va escriure sentint-la només dins del cap.",
 'historia', 2),
('Quina civilització va construir les piràmides de Gizeh?', "L'Antic Egipte", ['Els romans', 'Els grecs', 'Els maies'],
 "Es van aixecar fa uns 4.500 anys com a tombes dels faraons. Són tan antigues que Cleòpatra en va viure més a prop del nostre temps que del seu.",
 'historia', 1),
('Quin poble va construir el Colosseu de Roma?', 'Els romans', ['Els grecs', 'Els etruscs', 'Els cartaginesos'],
 "El van acabar l'any 80 i hi cabien unes 50.000 persones. Tenia un sistema de passadissos que permetia buidar-lo en pocs minuts.",
 'historia', 1),
('En quin país es va inventar el paper?', 'A la Xina', ['A Egipte', 'A Grècia', "A l'Índia"],
 "Els xinesos el van fabricar fa uns dos mil anys i en van guardar el secret durant segles. També van ser els primers a fer servir paper moneda.",
 'historia', 2),
('Quin pintor es va tallar part d’una orella?', 'Van Gogh', ['Monet', 'Cézanne', 'Gauguin'],
 "Vincent van Gogh, el 1888, en una crisi. Va vendre molt pocs quadres en vida i avui són dels més cars del món.",
 'historia', 2),

# ══════════════ LLENGUA ══════════════
("Quantes lletres té l'alfabet català?", '26', ['24', '28', '30'],
 "Vint-i-sis. Grups com ny, ll o ss sonen com una sola lletra però no compten a part: són dues lletres escrites juntes.",
 'llengua', 1),
('Què és un sinònim?', 'Una paraula que vol dir el mateix', ['Una paraula que vol dir el contrari',
 'Una paraula que sona igual', 'Una paraula inventada'],
 "Sinònim vol dir el mateix (content i alegre); antònim vol dir el contrari (content i trist).",
 'llengua', 0),
('Quantes vocals té el català?', '5', ['3', '6', '8'],
 "Cinc vocals escrites: a, e, i, o, u. Una altra cosa és com sonen: la e i la o es pronuncien obertes o tancades segons la paraula.",
 'llengua', 1),
('Què és un verb?', 'Una paraula que indica una acció', ['Una paraula que anomena una cosa',
 'Una paraula que descriu com és una cosa', 'Una paraula que uneix frases'],
 "El verb és el que es fa: córrer, menjar, pensar. El que anomena coses és el substantiu i el que descriu com són, l'adjectiu.",
 'llengua', 1),
('Quina d’aquestes paraules és un adjectiu?', 'Alt', ['Taula', 'Córrer', 'Ràpidament'],
 "L'adjectiu diu com és una cosa: una casa *alta*. Taula és un substantiu, córrer un verb i ràpidament un adverbi.",
 'llengua', 2),
('Què és una metàfora?', 'Dir una cosa amb la imatge d’una altra', ['Repetir una paraula',
 'Exagerar una cosa', 'Escriure a l’inrevés'],
 'Quan dius "tens un cor d’or" no parles de metall: fas servir la imatge de l’or per dir que la persona és bona.',
 'llengua', 2),
('En quin signe s’acaba una pregunta escrita?', "Un signe d'interrogació", ['Un punt', 'Una coma', 'Un guionet'],
 "El signe d'interrogació (?) tanca les preguntes. En català només se'n posa al final, no al principi.",
 'llengua', 0),
('Quin és el plural de "llapis"?', 'llapis', ['llapissos', 'llapisos', 'llàpissos'],
 "Les paraules que ja acaben en essa i no porten accent a l'última síl·laba no canvien en plural: un llapis, dos llapis. Igual que un dilluns, dos dilluns.",
 'llengua', 2),
('Què vol dir "matiner"?', 'Que es lleva aviat', ['Que arriba tard', 'Que dorm molt', 'Que treballa de nit'],
 "Ve de matí. Una persona matinera és la que es lleva d'hora, tant si li agrada com si no li queda més remei.",
 'llengua', 1),
('Quina paraula és el contrari de "generós"?', 'Garrepa', ['Ric', 'Alegre', 'Prudent'],
 "Generós és qui dona fàcilment; garrepa, qui no vol deixar anar res. Ser ric o pobre no hi té res a veure.",
 'llengua', 2),
# ══════════════ AMPLIACIÓ: sobretot nivell fàcil ══════════════
('Quin animal lladra?', 'El gos', ['El gat', 'El cavall', "L'ocell"],
 "El gos lladra; el gat miola, el cavall renilla i les ovelles belen. Cada animal té el seu so i la llengua té un verb per a cadascun.",
 'natura', 0),
('On viuen els peixos?', "A l'aigua", ['A l\u2019arbre', 'Sota terra', 'Als núvols'],
 "Els peixos respiren l'oxigen que hi ha dissolt a l'aigua, a través de les brànquies. Fora de l'aigua s'ofeguen encara que hi hagi aire.",
 'natura', 0),
('Quin animal té trompa?', "L'elefant", ['El lleó', 'El camell', 'El ren'],
 "La trompa de l'elefant és alhora nas i mà: hi respira, hi olora, beu, i pot agafar tant un tronc com una cacauet.",
 'natura', 0),
('Quantes ales té un ocell?', '2', ['1', '4', '6'],
 "Dues. Els insectes, en canvi, en solen tenir quatre, encara que a les mosques el segon parell s'ha convertit en dos balancins diminuts.",
 'natura', 0),
('Què surt d\u2019un ou de gallina?', 'Un pollet', ['Un conill', 'Un peix', 'Una papallona'],
 "Si l'ou està fecundat i la gallina el cova unes tres setmanes, en surt un pollet. Els ous que comprem no estan fecundats i no en sortiria res.",
 'natura', 0),
('De quin color és la neu?', 'Blanca', ['Blava', 'Verda', 'Groga'],
 "Els cristalls de gel reflecteixen tots els colors de la llum alhora, i la barreja de tots els colors és el blanc.",
 'natura', 0),
('Quin és l\u2019astre que ens dona llum de dia?', 'El Sol', ['La Lluna', 'Mart', 'Venus'],
 "El Sol és un estel: fa llum pròpia. La Lluna no en fa, només reflecteix la del Sol, i per això de nit fa aquella claror tan fluixa.",
 'mon', 0),
('Quants dies té una setmana?', '7', ['5', '6', '10'],
 "Set. És l'única mesura del calendari que no ve del cel: els mesos vénen de la Lluna i els anys del Sol, però la setmana és un invent humà molt antic.",
 'mon', 0),
('Quin mes ve després del desembre?', 'El gener', ['El novembre', 'El febrer', "L'octubre"],
 "El gener, que ja és de l'any següent. Es diu així per Janus, un déu romà amb dues cares: una mirava enrere i l'altra endavant.",
 'mon', 0),
('Quantes hores té un dia?', '24', ['12', '20', '36'],
 "Vint-i-quatre, que és el que triga la Terra a fer una volta sobre ella mateixa. Per això mentre aquí és de dia, a l'altra banda del món és de nit.",
 'mon', 0),
('Quin idioma es parla al Brasil?', 'El portuguès', ["L'espanyol", 'El brasiler', 'El francès'],
 "El Brasil va ser colònia de Portugal, i per això és l'únic país gran d'Amèrica del Sud que no parla espanyol.",
 'mon', 1),
('Quants minuts té una hora?', '60', ['50', '100', '30'],
 "Seixanta, com els segons d'un minut. Ve dels babilonis, que comptaven de seixanta en seixanta perquè el 60 es pot partir de moltes maneres.",
 'mon', 0),
('Quin invent serveix per saber l\u2019hora?', 'El rellotge', ['El termòmetre', 'La brúixola', 'La balança'],
 "El termòmetre mesura la temperatura, la brúixola indica el nord i la balança pesa. Cada aparell, la seva mesura.",
 'historia', 0),
('Amb què escrivien els nens a l\u2019escola fa cent anys?', 'Amb guix i pissarra', ['Amb ordinador',
 'Amb retolador', 'Amb bolígraf'],
 "Cada nen tenia una pissarreta pròpia i un guix, perquè el paper era car. S'escrivia, es mirava i s'esborrava per tornar a començar.",
 'historia', 0),
('Qui va pintar la Gioconda?', 'Leonardo da Vinci', ['Miquel Àngel', 'Rafael', 'Botticelli'],
 "Leonardo la va començar cap al 1503 i la va anar retocant anys i panys. No la va lliurar mai: se la va endur a França i allà s'ha quedat.",
 'historia', 1),
('Què és una catedral?', 'Una església gran', ['Un castell', 'Un mercat', 'Un teatre'],
 "És l'església principal d'una diòcesi, la que té la seu del bisbe. Per això a Barcelona, Girona o Tarragona també se'n diu la Seu.",
 'historia', 0),
('Quin aparell va inventar Gutenberg?', 'La impremta', ['El telescopi', 'El telèfon', 'La bicicleta'],
 "Cap al 1450 va idear els tipus mòbils: lletres soltes de metall que es podien recol·locar. Fins llavors, cada llibre s'havia de copiar a mà.",
 'historia', 2),
('Quin mitjà de transport va fer famós el Titanic?', 'El vaixell', ["L'avió", 'El tren', 'El globus'],
 "El Titanic era un transatlàntic i es va enfonsar el 1912 en el seu primer viatge, en xocar amb un iceberg.",
 'historia', 1),
('Com es diu la primera lletra de l\u2019abecedari?', 'La a', ['La be', 'La zeta', 'La ema'],
 "La a. La paraula *abecedari* és, de fet, el nom de les quatre primeres lletres seguides: a, be, ce, de.",
 'llengua', 0),
('Quantes paraules té la frase "el gat dorm"?', '3', ['2', '4', '5'],
 "Tres: *el*, *gat* i *dorm*. Les paraules se separen amb espais, encara que siguin tan curtes com *el*.",
 'llengua', 0),
('Què és el contrari de "dia"?', 'Nit', ['Tarda', 'Hora', 'Sol'],
 "Dia i nit són contraris. Tarda i hora no ho són: la tarda és un tros del dia i l'hora és una mesura.",
 'llengua', 0),
('Com es diu la persona que escriu llibres?', 'Escriptor', ['Lector', 'Llibreter', 'Impressor'],
 "L'escriptor l'escriu, l'impressor l'imprimeix, el llibreter el ven i el lector el llegeix. Cadascú té el seu nom.",
 'llengua', 0),
('Quantes síl·labes té la paraula "finestra"?', '3', ['2', '4', '5'],
 "Tres: fi-nes-tra. Les síl·labes són els cops de veu; es poden comptar picant de mans mentre es diu la paraula a poc a poc.",
 'llengua', 1),
('Què és un refrany?', 'Una dita curta amb una ensenyança', ['Una cançó', 'Un conte llarg', 'Una pregunta'],
 'Com "qui no vol pols, que no vagi a l\u2019era": una frase breu que guarda una experiència repetida durant generacions.',
 'llengua', 1),
('Què vol dir "matinar"?', 'Llevar-se molt aviat', ['Dinar tard', 'Dormir la migdiada', 'Sopar d\u2019hora'],
 "Ve de matí, com matiner. El refrany diu que a qui matina, Déu l'ajuda, que és una manera d'animar a començar aviat.",
 'llengua', 1),
# ══════════════ AMPLIACIÓ NATURA ══════════════
('Quantes potes té un gos?', '4', ['2', '6', '8'],
 "Quatre, com la majoria de mamífers de terra. Els ocells en tenen dues i les aranyes, vuit.",
 'natura', 0),
('On viuen les abelles?', 'Al rusc', ['Al niu', 'Al cau', 'A la conquilla'],
 "Al rusc, que fabriquen elles mateixes amb cera. Els ocells fan niu, els conills cau i els cargols porten la conquilla a sobre.",
 'natura', 0),
('Quin animal porta la casa a sobre?', 'El cargol', ['La formiga', 'La granota', 'El ratolí'],
 "El cargol i la tortuga porten la closca enganxada al cos: no és una casa que es puguin treure, sinó part de l'esquelet.",
 'natura', 0),
('Quin arbre fa pinyes?', 'El pi', ['El roure', "L'alzina", 'El pollancre'],
 "Les pinyes són el fruit dels pins i guarden els pinyons a dins. El roure i l'alzina fan aglans.",
 'natura', 0),
('Què menja una vaca?', 'Herba', ['Carn', 'Peix', 'Insectes'],
 "Herba i farratge. Té quatre compartiments a l'estómac i remuga: es torna a passar el menjar per la boca per acabar-lo de desfer.",
 'natura', 0),
('Quin animal té plomes?', "L'ocell", ['El gos', 'El peix', 'La serp'],
 "Només els ocells tenen plomes. Els mamífers tenen pèl, els peixos escates i els rèptils, plaques.",
 'natura', 0),
('Quin animal és mamífer però viu al mar?', 'El dofí', ['El tauró', 'La sardina', 'El pop'],
 "El dofí i la balena respiren aire pels pulmons i alleten les cries, com nosaltres. Han de pujar a la superfície per respirar.",
 'natura', 1),
('Quantes ales té una papallona?', '4', ['2', '6', '8'],
 "Quatre: dues de davant i dues de darrere. Com que es mouen alhora, de lluny sembla que només en tingui dues.",
 'natura', 1),
('Quin òrgan filtra la sang i fa l\u2019orina?', 'El ronyó', ['El fetge', 'El pàncrees', "L'estómac"],
 "En tenim dos. Filtren tota la sang del cos unes trenta vegades cada dia i en treuen el que sobra.",
 'natura', 1),
('Quin sentit tenim al nas?', "L'olfacte", ["L'oïda", 'El gust', 'El tacte'],
 "L'olfacte. Va molt lligat al gust: amb el nas tapat, el menjar perd gairebé tot el sabor.",
 'natura', 1),
('De quin arbre surten les castanyes?', 'Del castanyer', ["De l'avellaner", 'Del noguer', 'Del pi'],
 "Del castanyer. Cada fruit ve dins d'una bola plena de punxes que s'obre quan la castanya és a punt.",
 'natura', 1),
('Què li passa a l\u2019aigua quan es congela?', 'Augmenta de volum', ['Es fa més petita', 'Es torna més pesada', 'No canvia'],
 "Ocupa més lloc que quan és líquida, i per això el gel sura i una ampolla plena es pot esquerdar al congelador.",
 'natura', 1),
('Quin animal fa la teranyina?', "L'aranya", ['El cuc de seda', 'La formiga', 'La papallona'],
 "L'aranya la fabrica amb un fil que surt del seu propi cos i que, pel gruix que té, és més resistent que l'acer.",
 'natura', 1),
('Quin animal té el coll més llarg?', 'La girafa', ["L'estruç", 'El camell', 'El cigne'],
 "La girafa. Curiosament té les mateixes set vèrtebres al coll que nosaltres, però cadascuna fa més de vint centímetres.",
 'natura', 1),
('Quin animal pon ous i alhora dona llet?', "L'ornitorinc", ['El dofí', 'La tortuga', 'El pingüí'],
 "L'ornitorinc és un mamífer que pon ous, cosa rara: quan els europeus en van rebre el primer exemplar, van pensar que era una broma.",
 'natura', 2),
('Quina és la unitat més petita d\u2019un ésser viu?', 'La cèl·lula', ["L'òrgan", 'El teixit', 'La molècula'],
 "La cèl·lula. Hi ha éssers vius d'una sola cèl·lula, i una persona en té desenes de bilions.",
 'natura', 2),
('Quin òrgan fabrica la insulina?', 'El pàncrees', ['El fetge', 'El ronyó', 'La melsa'],
 "El pàncrees. La insulina controla el sucre de la sang; quan el cos no en fabrica prou, apareix la diabetis.",
 'natura', 2),
('Quin gas forma la major part de l\u2019aire?', 'El nitrogen', ["L'oxigen", 'El diòxid de carboni', "L'hidrogen"],
 "El nitrogen, que ocupa gairebé quatre cinquenes parts de l'aire. L'oxigen, que és el que respirem, només n'és una cinquena part.",
 'natura', 2),
('Quin és l\u2019òrgan més gran del cos humà?', 'La pell', ['El fetge', 'El pulmó', "L'intestí"],
 "La pell. En un adult pesa uns quatre quilos i es va renovant: les cèl·lules de fora cauen i en surten de noves per sota.",
 'natura', 2),
('Quin animal té tres cors?', 'El pop', ['La balena', 'El cocodril', "L'elefant"],
 "El pop. Dos cors envien la sang a les brànquies i el tercer la reparteix pel cos. A més, té la sang blava.",
 'natura', 2),
('Quina vitamina fabrica el cos amb la llum del sol?', 'La vitamina D', ['La vitamina C', 'La vitamina A', 'La vitamina B'],
 "La D, que ajuda a fixar el calci als ossos. És l'única que el cos pot fabricar tot sol, amb una estona de sol a la pell.",
 'natura', 2),
('Què mesura l\u2019escala de Richter?', 'Els terratrèmols', ['El vent', 'La pluja', 'La temperatura'],
 "La força dels terratrèmols. No és una escala normal: cada punt més vol dir deu vegades més moviment.",
 'natura', 2),
('Com es diu el pas de líquid a gas?', 'Evaporació', ['Condensació', 'Fusió', 'Solidificació'],
 "Evaporació. El camí contrari, de gas a líquid, és la condensació: és el que passa als vidres freds de la finestra.",
 'natura', 2),
('Quants cromosomes té una persona?', '46', ['23', '64', '12'],
 "Quaranta-sis, en vint-i-tres parelles: de cada parella, un ve del pare i l'altre de la mare.",
 'natura', 2),
# ══════════════ AMPLIACIÓ MÓN ══════════════
('Quants mesos té un any?', '12', ['10', '11', '14'],
 "Dotze. Els noms vénen dels romans, i per això setembre, octubre, novembre i desembre porten a dins el set, el vuit, el nou i el deu.",
 'mon', 0),
('Quants dies té un any normal?', '365', ['360', '350', '370'],
 "Tres-cents seixanta-cinc. La Terra en triga una mica més a fer la volta al Sol, i per això cada quatre anys s'hi afegeix un dia.",
 'mon', 0),
('Per on surt el sol?', 'Per l\u2019est', ['Per l\u2019oest', 'Pel nord', 'Pel sud'],
 "Sempre per l'est i es pon per l'oest. No és que el sol es mogui: som nosaltres, que girem.",
 'mon', 0),
('Quina és la capital d\u2019Itàlia?', 'Roma', ['Milà', 'Venècia', 'Nàpols'],
 "Roma, que a dins té un altre estat sencer, el Vaticà. Milà és la capital econòmica del país, però no la política.",
 'mon', 0),
('Què fem servir per saber on és el nord?', 'La brúixola', ['El termòmetre', 'El rellotge', 'La balança'],
 "La brúixola. L'agulla està imantada i s'orienta sola cap al nord, perquè la Terra sencera funciona com un imant.",
 'mon', 0),
('Quantes hores hi ha en mig dia?', '12', ['6', '10', '24'],
 "Dotze. Per això els rellotges d'agulles fan dues voltes senceres cada dia.",
 'mon', 0),
('Quina és la capital de Portugal?', 'Lisboa', ['Porto', 'Coïmbra', 'Braga'],
 "Lisboa, a la desembocadura del Tajo. És una de les ciutats més antigues d'Europa, més que Roma.",
 'mon', 1),
('En quin continent és el Japó?', 'Àsia', ['Oceania', 'Amèrica', 'Europa'],
 "A Àsia. És un arxipèlag de milers d'illes, però gairebé tota la gent viu a les quatre més grans.",
 'mon', 1),
('Quin riu passa per París?', 'El Sena', ['El Roine', 'El Loira', 'El Rin'],
 "El Sena. La ciutat va néixer en una illa enmig del riu, que és on avui hi ha la catedral de Notre-Dame.",
 'mon', 1),
('Quin monument és el símbol de París?', 'La torre Eiffel', ['El Big Ben', 'El Coliseu', 'La Sagrada Família'],
 "La torre Eiffel, construïda el 1889 per a una exposició. Havia de ser provisional i es volia desmuntar al cap de vint anys.",
 'mon', 1),
('Quina és la capital del Regne Unit?', 'Londres', ['Manchester', 'Edimburg', 'Liverpool'],
 "Londres. Edimburg és la capital d'Escòcia, que forma part del Regne Unit però té parlament propi.",
 'mon', 1),
('Quin oceà hi ha entre Europa i Amèrica?', "L'Atlàntic", ['El Pacífic', "L'Índic", 'El Mediterrani'],
 "L'Atlàntic. És el que van travessar Colom i, segles després, els primers vols entre els dos continents.",
 'mon', 1),
('Quin és el planeta vermell?', 'Mart', ['Venus', 'Júpiter', 'Mercuri'],
 "Mart. El color li ve del ferro rovellat del terra: literalment, és un planeta ple de rovell.",
 'mon', 1),
('Quina serralada separa la península Ibèrica de la resta d\u2019Europa?', 'Els Pirineus', ['Els Alps', 'Els Carpats', 'Els Apenins'],
 "Els Pirineus, que van del Mediterrani al Cantàbric. Andorra és a dalt de tot, entre Espanya i França.",
 'mon', 1),
('Quin és el planeta més gran del sistema solar?', 'Júpiter', ['Saturn', 'La Terra', 'Neptú'],
 "Júpiter. Hi cabrien més de mil Terres a dins, i té una tempesta més gran que el nostre planeta que dura segles.",
 'mon', 1),
('Quin és el país més petit del món?', 'El Vaticà', ['Mònaco', 'San Marino', 'Malta'],
 "El Vaticà, que ocupa menys de mig quilòmetre quadrat dins de Roma. S'hi pot donar la volta a peu en una estona.",
 'mon', 2),
('Quina és la capital del Canadà?', 'Ottawa', ['Toronto', 'Montreal', 'Vancouver'],
 "Ottawa. Es va triar justament perquè no era ni la ciutat més gran ni la més poderosa, i així ningú s'hi va oposar.",
 'mon', 2),
('Quin és el riu més llarg d\u2019Àfrica?', 'El Nil', ['El Congo', 'El Níger', 'El Zambezi'],
 "El Nil, que travessa el desert de sud a nord. Egipte hi va néixer al voltant, perquè les seves crescudes fertilitzaven la terra.",
 'mon', 2),
('Quina serralada travessa Amèrica del Sud de nord a sud?', 'Els Andes', ['Les Rocalloses', "L'Himàlaia", 'Els Urals'],
 "Els Andes, la serralada més llarga del món: més de set mil quilòmetres seguits al llarg de la costa del Pacífic.",
 'mon', 2),
('En quin oceà és l\u2019illa de Madagascar?', "A l'Índic", ["A l'Atlàntic", 'Al Pacífic', "A l'Àrtic"],
 "A l'Índic, davant de la costa d'Àfrica. Fa tants milions d'anys que està separada que hi viuen animals que no hi ha enlloc més.",
 'mon', 2),
('Quina és la capital de Turquia?', 'Ankara', ['Istanbul', 'Esmirna', 'Bursa'],
 "Ankara. Istanbul és molt més gran i coneguda, però la capital es va traslladar a Ankara el 1923.",
 'mon', 2),
('Quin canal uneix el Mediterrani amb el mar Roig?', 'El de Suez', ['El de Panamà', 'El de Corint', 'El de Kiel'],
 "El canal de Suez, obert el 1869. Evita haver de fer la volta sencera a Àfrica per anar d'Europa a Àsia.",
 'mon', 2),
('Quin estret separa Àsia d\u2019Amèrica?', 'Bering', ['Gibraltar', 'Magallanes', 'Bòsfor'],
 "L'estret de Bering. Fa uns 85 quilòmetres i, en plena glaciació, era terra ferma: per allà van passar els primers pobladors d'Amèrica.",
 'mon', 2),
('Quin continent no té cap país?', "L'Antàrtida", ['Oceania', "L'Àfrica", "L'Àsia"],
 "L'Antàrtida. Un tractat internacional la reserva per a la ciència i prohibeix que ningú se'n faci l'amo.",
 'mon', 2),
('Quin és el punt més fondo dels oceans?', 'La fossa de les Mariannes', ['El mar dels Sargassos', 'La fossa de Puerto Rico', 'El golf de Bengala'],
 "La fossa de les Mariannes, al Pacífic: passa dels 10.000 metres. Si hi posessis l'Everest a dins, encara quedaria cobert d'aigua.",
 'mon', 2),
# ══════════════ AMPLIACIÓ HISTÒRIA I ART ══════════════
('Què escoltava la gent abans que hi hagués televisió?', 'La ràdio', ['El telèfon', 'El tocadiscos', 'El cinema'],
 "La ràdio. Les famílies s'hi asseien al voltant a la nit per sentir notícies, música i fins i tot novel·les llegides.",
 'historia', 0),
('Com es viatjava per terra abans del tren?', 'Amb cavall i carro', ['Amb bicicleta', 'Amb globus', 'A peu i prou'],
 "Amb cavalls i carruatges. Un viatge que avui es fa en una hora podia durar dos dies, amb parades per canviar els cavalls.",
 'historia', 0),
('Quin animal feia servir la gent per llaurar el camp abans del tractor?', 'El bou', ['El gos', "L'ovella", 'La gallina'],
 "El bou i la mula. Eren tan valuosos que una família de pagès podia estar-hi endeutada tota la vida.",
 'historia', 0),
('Quin joc es juga en un tauler de 64 caselles?', 'Els escacs', ['El parxís', 'Les dames xineses', 'El dòmino'],
 "Els escacs, amb setze peces per banda. Ve de l'Índia, fa més de mil cinc-cents anys, i les regles actuals són del segle XV.",
 'historia', 0),
('Quin aparell serveix per parlar amb algú que és lluny?', 'El telèfon', ['El termòmetre', 'El microscopi', 'El baròmetre'],
 "El telèfon. Els primers eren fixos i compartits: en molts pobles n'hi havia un per a tothom.",
 'historia', 0),
('Què és un museu?', 'Un lloc on es guarden i s\u2019ensenyen obres', ['Una escola de dibuix', 'Una botiga de quadres', 'Un taller de pintors'],
 "Un lloc que conserva obres i objectes i els ensenya al públic. La paraula ve de les muses, les deesses gregues de les arts.",
 'historia', 0),
('Quin instrument es toca prement tecles?', 'El piano', ['El violí', 'La trompeta', 'El tambor'],
 "El piano. Cada tecla mou un martellet que colpeja una corda: per dins, és alhora instrument de corda i de percussió.",
 'historia', 0),
('Quin esport es juga encistellant una pilota?', 'El bàsquet', ['El futbol', 'El tennis', 'El handbol'],
 "El bàsquet, inventat el 1891 en un gimnàs amb dues cistelles de fruita clavades a la paret; d'aquí li ve el nom.",
 'historia', 0),
('De què està feta una escultura de marbre?', 'De pedra', ['De fusta', 'De metall', 'De vidre'],
 "El marbre és una pedra. L'escultor no hi afegeix res: només en treu el que sobra fins que apareix la figura.",
 'historia', 0),
('Qui va ser el primer home a trepitjar la Lluna?', 'Neil Armstrong', ['Iuri Gagarin', 'Buzz Aldrin', 'John Glenn'],
 "Neil Armstrong, seguit minuts després per Buzz Aldrin. Gagarin havia estat el primer home a l'espai, vuit anys abans.",
 'historia', 0),
('Quina llengua parlaven els antics romans?', 'El llatí', ['El grec', "L'italià", "L'àrab"],
 "El llatí. D'ell en vénen el català, el castellà, el francès, l'italià, el portuguès i el romanès.",
 'historia', 1),
('Quin poble va construir els aqüeductes que encara es veuen a Europa?', 'Els romans', ['Els grecs', 'Els àrabs', 'Els víkings'],
 "Els romans. Portaven aigua a les ciutats amb un pendent d'uns pocs centímetres per quilòmetre, calculat a mà.",
 'historia', 1),
('Quin animal era sagrat a l\u2019antic Egipte?', 'El gat', ['El gos', 'El cavall', 'El porc'],
 "El gat, que protegia els graners dels ratolins. Matar-ne un es castigava amb la mort, i quan moria la família feia dol.",
 'historia', 1),
('Qui va arribar a Amèrica el 1492?', 'Cristòfol Colom', ['Magallanes', 'Marco Polo', 'Vasco de Gama'],
 "Colom, buscant un camí cap a Àsia per l'oest. Va morir convençut que havia arribat a les Índies.",
 'historia', 1),
('Qui va pintar el sostre de la Capella Sixtina?', 'Miquel Àngel', ['Leonardo da Vinci', 'Rafael', 'Botticelli'],
 "Miquel Àngel, en quatre anys, dret dalt d'una bastida. Ell es considerava escultor i va acceptar l'encàrrec de mala gana.",
 'historia', 1),
('Quin instrument va perfeccionar Stradivari?', 'El violí', ['El piano', 'La flauta', "L'orgue"],
 "El violí. Encara avui ningú ha sabut repetir exactament el seu so, i els seus instruments valen milions.",
 'historia', 1),
('Qui va escriure Romeu i Julieta?', 'Shakespeare', ['Molière', 'Dante', 'Goethe'],
 "William Shakespeare, cap al 1595. Al seu teatre els papers de dona els feien nois, perquè les dones no hi podien actuar.",
 'historia', 1),
('En quin país es van celebrar els primers Jocs Olímpics moderns?', 'A Grècia', ['A França', 'A Anglaterra', "A Itàlia"],
 "A Atenes, el 1896, en record dels jocs de l'antiga Grècia, que se celebraven a Olímpia cada quatre anys.",
 'historia', 1),
('Quin invent va permetre navegar sense veure la costa?', 'La brúixola', ['El telescopi', 'El rellotge de sorra', 'El timó'],
 "La brúixola, que arriba d'Àsia a l'edat mitjana. Fins llavors els vaixells procuraven no perdre la terra de vista.",
 'historia', 1),
('Quin edifici de Barcelona és obra de Gaudí?', 'La Pedrera', ['El Palau de la Música', "L'Hospital de Sant Pau", "L'Arc de Triomf"],
 "La Pedrera, o Casa Milà, sense una sola línia recta a la façana. El Palau de la Música i Sant Pau són de Domènech i Montaner.",
 'historia', 1),
('En quin any va començar la Primera Guerra Mundial?', '1914', ['1918', '1910', '1920'],
 "El 1914, i va durar fins al 1918. Es deia que seria curta i que els soldats serien a casa per Nadal.",
 'historia', 2),
('Qui va ser el primer emperador romà?', 'August', ['Juli Cèsar', 'Neró', 'Trajà'],
 "August, fill adoptiu de Juli Cèsar. Cèsar mai no va ser emperador: el van matar abans, quan era dictador.",
 'historia', 2),
('En quin any es va acabar la Segona Guerra Mundial?', '1945', ['1939', '1942', '1950'],
 "El 1945, primer a Europa al maig i després al Pacífic al setembre. Havia començat el 1939.",
 'historia', 2),
('Qui va ser la primera dona a guanyar un premi Nobel?', 'Marie Curie', ['Rosalind Franklin', 'Ada Lovelace', 'Florence Nightingale'],
 "Marie Curie, el 1903 en física. Encara avui és l'única persona que n'ha guanyat dos en dues ciències diferents.",
 'historia', 2),
('Quin moviment artístic van fundar Picasso i Braque?', 'El cubisme', ["L'impressionisme", 'El surrealisme', 'El romanticisme'],
 "El cubisme, cap al 1907. Pinten un mateix objecte des de diversos punts de vista alhora, i per això sembla trencat.",
 'historia', 2),
('Quin compositor va escriure Les quatre estacions?', 'Vivaldi', ['Mozart', 'Bach', 'Haydn'],
 "Antonio Vivaldi, cap al 1720. Cada concert va acompanyat d'un poema, i la música imita ocells, tempestes i gent patinant.",
 'historia', 2),
('Quin filòsof grec va ser mestre d\u2019Alexandre el Gran?', 'Aristòtil', ['Plató', 'Sòcrates', 'Pitàgores'],
 "Aristòtil. La cadena és curiosa: Sòcrates va ensenyar Plató, Plató va ensenyar Aristòtil i Aristòtil, Alexandre.",
 'historia', 2),
('Qui va pintar La nit estrellada?', 'Van Gogh', ['Monet', 'Munch', 'Klimt'],
 "Van Gogh, el 1889, des de la finestra de l'hospital on estava ingressat. El poble del quadre se'l va inventar.",
 'historia', 2),
('Quin poeta català va escriure L\u2019Atlàntida?', 'Jacint Verdaguer', ['Ausiàs March', 'Joan Maragall', 'Salvador Espriu'],
 "Jacint Verdaguer, el 1877. Explica l'enfonsament del continent llegendari i és una de les obres clau de la Renaixença.",
 'historia', 2),
('Quin tractat va repartir el món entre Espanya i Portugal?', 'El de Tordesillas', ['El de Versalles', 'El dels Pirineus', 'El de Roma'],
 "El de Tordesillas, del 1494: una ratlla al mapa de l'Atlàntic. Per això al Brasil es parla portuguès i a la resta del continent no.",
 'historia', 2),
# ══════════════ AMPLIACIÓ LLENGUA ══════════════
('Quantes lletres té la paraula "casa"?', '4', ['3', '5', '6'],
 "Quatre: c-a-s-a. Compten totes les lletres escrites, encara que n'hi hagi dues d'iguals.",
 'llengua', 0),
('Com acaba una frase que no és pregunta ni exclamació?', 'Amb un punt', ['Amb una coma', 'Amb dos punts', 'Amb un guionet'],
 "Amb un punt. La coma només fa una pausa dins la frase; el punt la tanca del tot.",
 'llengua', 0),
('Quin és el plural de "gat"?', 'gats', ['gates', 'gatos', 'gat'],
 "Gats. La majoria de paraules catalanes fan el plural afegint una essa al final.",
 'llengua', 0),
('Quantes síl·labes té la paraula "sol"?', '1', ['2', '3', '4'],
 "Una de sola. Les síl·labes són els cops de veu, i la paraula sol es diu d'una tirada.",
 'llengua', 0),
('Quina d\u2019aquestes paraules és una vocal?', 'e', ['b', 'm', 'r'],
 "Les vocals són a, e, i, o, u. La resta de lletres són consonants i necessiten una vocal a prop per poder-se dir.",
 'llengua', 0),
('Com es diu el conjunt de totes les lletres?', "L'abecedari", ['El diccionari', 'La gramàtica', 'El vocabulari'],
 "L'abecedari o alfabet. El diccionari recull paraules amb el seu significat; la gramàtica, les regles per combinar-les.",
 'llengua', 0),
('Quina d\u2019aquestes paraules anomena un animal?', 'gos', ['taula', 'verd', 'córrer'],
 "Gos. Taula és un objecte, verd és un color i córrer és una acció: cada paraula fa la seva feina dins la frase.",
 'llengua', 0),
('Què vol dir "escoltar"?', 'Parar atenció al que se sent', ['Parlar en veu alta', 'Mirar amb atenció', 'Escriure el que et diuen'],
 "Escoltar és sentir amb atenció i voluntat. Es pot sentir un soroll sense voler, però escoltar demana posar-hi interès.",
 'llengua', 0),
('Què és un substantiu?', 'Una paraula que anomena coses', ['Una paraula que indica acció',
 'Una paraula que descriu com és una cosa', 'Una paraula que uneix frases'],
 "El substantiu anomena persones, animals, objectes o idees: casa, Anna, alegria. L'acció la indica el verb.",
 'llengua', 0),
('Quin és el contrari de "gran"?', 'Petit', ['Ample', 'Alt', 'Llarg'],
 "Petit. Ample, alt i llarg parlen de mides concretes; gran i petit parlen de la mida en general.",
 'llengua', 0),
('Què és un adverbi?', 'Una paraula que diu com, quan o on', ['Una paraula que anomena coses',
 'Una paraula que indica acció', 'Una paraula que substitueix un nom'],
 "L'adverbi acompanya el verb i el matisa: parlar *a poc a poc*, venir *demà*, quedar-se *aquí*.",
 'llengua', 1),
('Quin és el femení de "cavall"?', 'euga', ['cavalla', 'cavalleta', 'poltra'],
 "Euga (també egua). Passa amb uns quants animals: el mascle i la femella tenen noms del tot diferents, com toro i vaca.",
 'llengua', 1),
('Quantes síl·labes té la paraula "ordinador"?', '4', ['3', '5', '6'],
 "Quatre: or-di-na-dor. Es poden comptar picant de mans mentre es diu la paraula a poc a poc.",
 'llengua', 1),
('Què és un diminutiu?', 'Una paraula que indica que una cosa és petita', ['Una paraula escrita en minúscula',
 'Una paraula curta', 'Una paraula mal dita'],
 "Un diminutiu es forma afegint un tros al final: casa → caseta, gos → gosset. Sovint també indica afecte.",
 'llengua', 1),
('Què és una rima?', 'Quan dues paraules acaben igual', ['Quan dues paraules comencen igual',
 'Quan dues paraules volen dir el mateix', 'Quan una paraula es repeteix'],
 "La rima és la coincidència dels sons finals: amor i dolor, cançó i il·lusió. És el que fa que un poema s'enganxi a la memòria.",
 'llengua', 1),
('Què és un prefix?', 'Un tros que es posa davant d\u2019una paraula', ['Un tros que es posa darrere',
 'La síl·laba forta', 'La primera lletra'],
 "El prefix va al davant i canvia el sentit: *des*fer, *re*llegir, *in*útil. El que va darrere és el sufix.",
 'llengua', 1),
('Quin és el femení de "gendre"?', 'nora', ['gendra', 'sogra', 'cunyada'],
 "Nora. El gendre és el marit de la filla i la nora, la dona del fill. La sogra és la mare de la parella.",
 'llengua', 1),
('Com es diu el so que fa el gat?', 'El miol', ['El bram', 'El grunyit', 'El xiscle'],
 "El gat miola. El burro brama, el porc grunyeix i el gos lladra: cada animal té el seu verb.",
 'llengua', 1),
('Quina d\u2019aquestes paraules està ben escrita?', 'cafè', ['café', 'cafe', 'càfe'],
 "Cafè, amb accent obert. En català, la e i la o porten accent obert o tancat segons com sonin.",
 'llengua', 1),
('Què vol dir "efímer"?', 'Que dura molt poc', ['Que dura per sempre', 'Que és molt petit', 'Que és molt car'],
 "Efímer vol dir de vida breu: una flor efímera, una moda efímera. El contrari seria durador o perenne.",
 'llengua', 2),
('Quin temps verbal és "cantava"?', "L'imperfet", ['El present', 'El futur', 'El condicional'],
 "El pretèrit imperfet, que explica accions repetides o que duraven: *cantava* cada dia. El passat acabat seria *va cantar*.",
 'llengua', 2),
('Què és una onomatopeia?', 'Una paraula que imita un so', ['Una paraula molt llarga',
 'Una paraula estrangera', 'Una paraula inventada per un escriptor'],
 "Paraules com xiuxiueig, catacrac o ronc imiten el soroll que anomenen. Cada llengua les fa a la seva manera.",
 'llengua', 2),
('Quin és el femení de "heroi"?', 'heroïna', ['heroia', 'heroa', 'heroina'],
 "Heroïna, amb dièresi a la i perquè es llegeixi separada de la o. Sense la dièresi es llegiria com un diftong.",
 'llengua', 2),
('Què és un sufix?', 'Un tros que es posa darrere d\u2019una paraula', ['Un tros que es posa davant',
 'Una paraula composta', 'Un accent'],
 "El sufix va al final i sovint canvia de categoria: de *fusta* surt *fuster*; de *cantar*, *cantant*.",
 'llengua', 2),
('Què és un homònim?', 'Paraules que sonen igual i volen dir coses diferents', ['Paraules que volen dir el mateix',
 'Paraules que volen dir el contrari', 'Paraules escrites al revés'],
 "Com *son* (dormir) i *son* (el seu). Els sinònims volen dir el mateix; els homònims només coincideixen en el so.",
 'llengua', 2),
('Quin és el contrari de "abundant"?', 'Escàs', ['Ampli', 'Divers', 'Constant'],
 "Escàs vol dir que n'hi ha poc. Abundant vol dir que n'hi ha de sobres, molt més del que caldria.",
 'llengua', 2),
('Què vol dir "tàcit"?', 'Que s\u2019entén sense dir-ho', ['Que es diu molt fort',
 'Que està escrit', 'Que és molt curt'],
 "Un acord tàcit és el que tothom dona per fet sense haver-lo parlat. Ve del llatí *tacere*, callar.",
 'llengua', 2),
('Quin és el plural de "reflex"?', 'reflexos', ['reflexs', 'reflexes', 'reflex'],
 "Reflexos. Les paraules acabades en x precedida de vocal afegeixen -os: annex → annexos, complex → complexos.",
 'llengua', 2),
('Què vol dir "perenne"?', 'Que dura tot l\u2019any o sempre', ['Que dura un dia',
 'Que floreix a la primavera', 'Que creix molt de pressa'],
 "Un arbre de fulla perenne no es queda pelat a l'hivern, com el pi. El contrari és de fulla caduca, com el plàtan.",
 'llengua', 2),
('Què és una comparació en literatura?', 'Dir que una cosa és com una altra', ['Repetir una paraula',
 'Dir el contrari del que es pensa', 'Escriure en vers'],
 'Fa servir un "com": *fort com un roure*. Si es treu el "com" i es diu directament que una cosa és l\u2019altra, ja és una metàfora.',
 'llengua', 2)
]

TEMES = ['natura', 'mon', 'historia', 'llengua']
NIVELLS = ['fàcil', 'mitjà', 'difícil']


def comprova():
    problemes, vistes = [], set()
    for i, (p, b, o, e, t, n) in enumerate(BANC):
        if p in vistes: problemes.append(f'{i}: pregunta repetida — {p}')
        vistes.add(p)
        if len(o) != 3: problemes.append(f'{i}: {len(o)} respostes dolentes — {p}')
        if b in o: problemes.append(f'{i}: la bona també és a les dolentes — {p}')
        if len(set(o)) != 3: problemes.append(f'{i}: dolentes repetides — {p}')
        if len(e) < 60: problemes.append(f'{i}: explicació massa curta — {p}')
        if t not in TEMES: problemes.append(f'{i}: tema desconegut {t}')
        if n not in (0, 1, 2): problemes.append(f'{i}: nivell desconegut {n}')
        if not p.endswith('?'): problemes.append(f'{i}: no acaba amb interrogant — {p}')
    return problemes


def js():
    """Escriu el banc tal com ha d'anar dins l'index.html"""
    def txt(s): return "'" + s.replace('\\', '\\\\').replace("'", "\\'") + "'"
    files = []
    for p, b, o, e, t, n in BANC:
        files.append('  {p:%s, b:%s, o:[%s], e:%s, t:%s, n:%d}'
                     % (txt(p), txt(b), ', '.join(txt(x) for x in o), txt(e), txt(t), n))
    return 'const BANC_PREGUNTES = [\n' + ',\n'.join(files) + '\n];\n'


if __name__ == '__main__':
    mals = comprova()
    print('preguntes:', len(BANC), '· problemes:', len(mals))
    for m in mals: print('  ', m)
    print()
    print('per tema i nivell:')
    print('  %-10s %6s %6s %6s' % ('tema', 'fàcil', 'mitjà', 'difícil'))
    for t in TEMES:
        c = [sum(1 for x in BANC if x[4] == t and x[5] == n) for n in (0, 1, 2)]
        print('  %-10s %6d %6d %6d' % (t, *c))
    print('  %-10s %6d %6d %6d' % ('TOTAL',
          *[sum(1 for x in BANC if x[5] == n) for n in (0, 1, 2)]))
    open('/tmp/claude-0/-home-claude/46257fec-254f-5388-a15a-a7d89661eb07/scratchpad/banc.js', 'w').write(js())
